### ISSUE TITLE
Inclusion of recent Transifex translations for de_DE

### ISSUE THREAD

**Issue by priojk** [DoliCloud/DoliMed#3]
I just made some changes to the German translations - there was a slight mixup of the wordings for consultations and examinations which lead to a confusing UI. - What is the process for pulling these translations from Transifex into the project? I know that for Dolibarr this happens automatically every few weeks. But in Dolimed the last updates are from a couple years ago. 

If I need to to something or if I can help in any way, pls let me know.

**Comment by eldy** [comment]
If translation were pushed in transifex. Nothing more to do. A manual sync will move them into the git project.
Thanks for your contributions
